### ISSUE TITLE
Meta: Migrate to a W3C Working Group

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/uuid#27]
As this spec is now widely implemented (Chromium, WebKit, Gecko), it would be nice to migrate it to a working group. 

@WICG/chairs, could you kindly help us find a home for it?

**Comment by marcoscaceres** [comment]
Looks like it’s in scope for the new WebAppsSec charter: https://www.w3.org/2021/06/webappsec-proposed-charter-2021.html#scope

So, perfect timing! 🎉

**Comment by yoavweiss** [comment]
@mikewest - thoughts on the above?

**Comment by mikewest** [comment]
> Looks like it’s in scope for the new WebAppsSec charter

_Proposed_ charter, modulo some formal objections.

But yes. This proposal was explicitly on my mind (as well as something like https://github.com/tQsW/webcrypto-curve25519/blob/master/explainer.md) when adding that to the proposal. I think WebAppSec is a fine place for the work.

/cc @dveditz @samuelweiler @sideshowbarker in case they have different recollections.

**Comment by sideshowbarker** [comment]
> /cc @dveditz @samuelweiler @sideshowbarker in case they have different recollections.

I believe your recollection is corrected

Also, heads-up to @twiss on this

**Comment by marcoscaceres** [comment]
Great. Once we have the charter situation resolved, I'm happy to help move this over. Just ping!

**Comment by bcoe** [comment]
@twiss question for you, when the charter is resolved, would you prefer that this is landed as a new specification referencing Web Cryptography, or as an addition to the spec?

**Comment by twiss** [comment]
I would somewhat prefer to add it to the existing spec - I think since `getRandomValues` and `randomUUID` are quite closely related it would seem nice to have them in the same spec (and e.g. the security and privacy considerations overlap).

**Comment by bcoe** [comment]
@twiss would you like me to start a straw person proposal against [webcrypto](https://github.com/w3c/webcrypto)?

**Comment by twiss** [comment]
Yeah, I would say go for it :+1:

**Comment by bcoe** [comment]
> Yeah, I would say go for it 👍

@twiss done https://github.com/w3c/webcrypto/pull/285 🎉

**Comment by domenic** [comment]
We're doing a minor project to clean up Googler-led incubations that have graduated or become inactive. Since this spec has successfully graduated, I've posted a few PRs to reflect that.

After they are merged, we should also update https://github.com/WICG/admin/blob/gh-pages/biblio.json , and then archive this repository.

**Comment by marcoscaceres** [comment]
Going ahead and archiving this repository. Further work should be taken up over in https://github.com/w3c/webcrypto/ (with potential new ideas incubated in the WICG with a new repo.)
