### ISSUE TITLE
Provide snapshot of generated spec on gh-pages

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/uuid#32]
(@marcoscaceres will set this up - just adding it so I don't forget)

Some folks find the ReSpec's flash of unstyled content a bit unpleasant. 

Similarly to BikeShed specs, to address this what we usually do is have two branches: 

 * "gh-pages" branch - hosts the static snapshop, which is then served to viewers.
 * "main" branch - where the editorial work happens, hosts the "raw" ReSpec spec.

We then use [spec-prod](http://github.com/w3c/spec-prod) to automatically generate the snapshot.

**Comment by marcoscaceres** [comment]
@bcoe, when possible, can you give me admin rights on the repo? I can then make all the above happen.

**Comment by bcoe** [comment]
@marcoscaceres you should have access, but perhaps we should wait to land on a resolution to #29 before we cut the new branch, if it will make #33 difficult to merge.

**Comment by marcoscaceres** [comment]
Yep, no problem. I'll set up the script and we can merge it when ready.

**Comment by bcoe** [comment]
@marcoscaceres snapshot seems to be working appropriately, only thing I was wondering about was whether we'll still get previews on PRs 👍

**Comment by marcoscaceres** [comment]
We definitely should. Weird that it stopped working. I’ll poke around and see if I can figure out what happened.

**Comment by marcoscaceres** [comment]
Confirmed fixed... closing as "works for me".
